# Generated by Django 2.0.5 on 2018-06-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pic',
            field=models.ImageField(blank=True, upload_to='product_pic'),
        ),
    ]
