# Generated by Django 2.0.5 on 2018-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_auto_20180625_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='books', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.CharField(default='books', max_length=255),
        ),
    ]
