# Generated by Django 2.0.5 on 2018-07-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_auto_20180701_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('rr_uname', models.CharField(max_length=255)),
                ('ratings', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
            ],
        ),
    ]
